// Forge — Phase 18V/18W: Substrate Attestation.
//
// OBSERVED substrate facts that prove an execution ran inside a real
// isolation boundary — not merely that a config variable said "sandbox".
// The worker OBSERVES kernel-level facts after entering the substrate and
// records them here. The control plane verifies them independently.
//
// The attestation is bound into the signed ExecutionEvidenceEnvelope (Phase
// 18F), so it is Ed25519-authenticated and execution-bound (Phase 18O).
//
// PRODUCTION GATE: executionEnvironmentSandboxed is now
// isSubstrateVerified(envelope.substrateAttestation) — replacing the Phase
// 18F hardcoded-false placeholder. No attestation => false => PRODUCTION_READY blocked.
//
// PHASE 18W: TWO-SIGNATURE TRUST MODEL.
// The launcher gets its OWN Ed25519 key (separate from the worker key,
// provisioned by admin). The launcher signs the observed facts + nonce +
// executionId + workload results (canonicalFactsJson). The worker includes
// the launcher-signed attestation in its envelope. The control plane verifies
// BOTH signatures via isSubstrateTrusted():
//   - verifySubstrateAttestation() checks the FACTS (fields are valid).
//   - verifyLauncherAttestation() checks the LAUNCHER SIGNATURE (facts came
//     from the real launcher, not fabricated by the worker).
// A compromised worker cannot manufacture a valid substrate claim — it does
// not have the launcher private key.

import {
  createHash,
  verify as cryptoVerify,
  generateKeyPairSync,
} from "node:crypto";

export type SubstrateType = "linux-namespace-sandbox" | "docker" | "none";

export const REQUIRED_SUBSTRATE_POLICY = {
  cpuLimitSeconds: 600,
  memoryLimitBytes: 2 * 1024 * 1024 * 1024,
  processLimit: 256,
  fileDescriptorLimit: 1024,
  fileSizeLimitBytes: 512 * 1024 * 1024,
  networkMode: "hermetic-loopback" as const,
  readonlyRootfs: true,
  blockedSyscalls: [
    "acct", "bpf", "delete_module", "finit_module", "init_module", "kcmp",
    "kexec_file_load", "kexec_load", "keyctl", "lookup_dcookie", "mount",
    "nfsservctl", "open_by_handle_at", "perf_event_open", "personality",
    "pivot_root", "ptrace", "quotactl", "reboot", "setns", "swapoff",
    "swapon", "umount2", "unshare", "vmsplice",
  ],
};

export function computeSeccompProfileHash(blockedSyscalls: string[]): string {
  const sorted = [...blockedSyscalls].sort();
  return createHash("sha256").update(sorted.join(",")).digest("hex");
}

export const REQUIRED_SECCOMP_PROFILE_HASH = computeSeccompProfileHash(
  REQUIRED_SUBSTRATE_POLICY.blockedSyscalls
);

export const REQUIRED_DROPPED_CAPABILITIES = [
  "cap_chown","cap_dac_override","cap_dac_read_search","cap_fowner","cap_fsetid",
  "cap_kill","cap_setgid","cap_setuid","cap_setpcap","cap_linux_immutable",
  "cap_net_bind_service","cap_net_broadcast","cap_net_admin","cap_net_raw",
  "cap_ipc_lock","cap_ipc_owner","cap_sys_module","cap_sys_rawio","cap_sys_chroot",
  "cap_sys_ptrace","cap_sys_pacct","cap_sys_admin","cap_sys_boot","cap_sys_nice",
  "cap_sys_resource","cap_sys_time","cap_sys_tty_config","cap_mknod","cap_lease",
  "cap_audit_write","cap_audit_control","cap_setfcap","cap_mac_override",
  "cap_mac_admin","cap_syslog","cap_wake_alarm","cap_block_suspend",
  "cap_audit_read","cap_perfmon","cap_bpf","cap_checkpoint_restore",
];

/**
 * Phase 18W: SandboxAttestation now includes launcher-signed fields.
 *
 * The launcher signs `canonicalFactsJson` (a deterministic JSON string with
 * sorted keys, no whitespace) with its OWN Ed25519 private key. The signature
 * covers: substrateFacts (nested), nonce, executionId, substrateInstanceId,
 * workloadExitCode, workloadSignal, workloadStdoutHash, workloadStderrHash,
 * signedAt.
 *
 * The control plane verifies the signature with a PINNED launcher public key
 * (provisioned by admin, NOT the worker). This proves the facts came from the
 * real launcher — a compromised worker cannot forge the signature.
 */
export interface SandboxAttestation {
  substrateType: SubstrateType;
  runtimeVersion: string;
  userNamespaceInode: string | null;
  pidNamespaceInode: string | null;
  netNamespaceInode: string | null;
  mntNamespaceInode: string | null;
  seccompMode: number;
  seccompProfileHash: string;
  cpuLimitSeconds: number;
  memoryLimitBytes: number;
  processLimit: number;
  fileDescriptorLimit: number;
  fileSizeLimitBytes: number;
  capabilitiesDropped: string[];
  networkMode: "hermetic-loopback" | "bridge" | "host";
  imageDigest?: string | null;
  containerId?: string | null;
  readonlyRootfs: boolean;
  createdAt: string;
  substrateVerified: boolean;

  // ---- Phase 18W: launcher trust fields (REQUIRED for non-null attestations) ----

  /** The nonce passed to the launcher. Bound into the launcher signature. */
  nonce: string;
  /** The executionId passed to the launcher. Bound into the launcher signature. */
  executionId: string;
  /** A UUID generated by runInSubstrate for this substrate invocation. */
  substrateInstanceId: string;
  /** The workload's exit code (null if killed by signal). */
  workloadExitCode: number | null;
  /** The signal that killed the workload (null if exited normally). */
  workloadSignal: number | null;
  /** SHA-256 hex of the workload's stdout. */
  workloadStdoutHash: string;
  /** SHA-256 hex of the workload's stderr. */
  workloadStderrHash: string;
  /** The exact canonical JSON string that was signed (sorted keys, no whitespace). */
  canonicalFactsJson: string;
  /** The Ed25519 signature over canonicalFactsJson UTF-8 bytes (hex). */
  launcherSignature: string;
  /** Always "ed25519". */
  launcherAlgorithm: string;
  /** Always "forge-launcher-v2" (identifies the launcher signing key). */
  launcherKeyId: string;
  /** ISO-UTC timestamp the launcher signed the facts. */
  launcherSignedAt: string;
}

export interface SubstrateVerificationResult {
  valid: boolean;
  reasons: string[];
}

const HOST_NAMESPACE_SENTINELS = new Set([
  "user:[4026531837]",
  "pid:[4026531836]",
  "net:[4026531994]",
  "mnt:[4026531840]",
]);

/**
 * Verify the substrate FACTS (field-level checks). This does NOT verify the
 * launcher signature — use verifyLauncherAttestation() for that, or
 * isSubstrateTrusted() for the combined check.
 */
export function verifySubstrateAttestation(
  attestation: SandboxAttestation | null | undefined
): SubstrateVerificationResult {
  const reasons: string[] = [];
  if (!attestation) {
    return { valid: false, reasons: ["No substrate attestation provided"] };
  }
  if (attestation.substrateType === "none") {
    reasons.push("substrateType is 'none' — no physical isolation");
  } else if (
    attestation.substrateType !== "linux-namespace-sandbox" &&
    attestation.substrateType !== "docker"
  ) {
    reasons.push(`Unknown substrateType: ${attestation.substrateType}`);
  }
  if (!attestation.substrateVerified) {
    reasons.push("Worker self-check substrateVerified is false");
  }
  const nsFields: Array<[string, string | null]> = [
    ["userNamespaceInode", attestation.userNamespaceInode],
    ["pidNamespaceInode", attestation.pidNamespaceInode],
    ["netNamespaceInode", attestation.netNamespaceInode],
    ["mntNamespaceInode", attestation.mntNamespaceInode],
  ];
  for (const [name, inode] of nsFields) {
    if (!inode) {
      reasons.push(`${name} is missing`);
    } else if (HOST_NAMESPACE_SENTINELS.has(inode)) {
      reasons.push(`${name} (${inode}) matches a host sentinel — NOT in a new namespace`);
    }
  }
  if (attestation.seccompMode !== 2) {
    reasons.push(`seccompMode is ${attestation.seccompMode} (required: 2)`);
  }
  if (attestation.seccompProfileHash !== REQUIRED_SECCOMP_PROFILE_HASH) {
    reasons.push("seccompProfileHash does not match the required filter");
  }
  if (!Number.isFinite(attestation.cpuLimitSeconds)) reasons.push("cpuLimitSeconds unlimited");
  if (!Number.isFinite(attestation.memoryLimitBytes)) reasons.push("memoryLimitBytes unlimited");
  if (!Number.isFinite(attestation.processLimit)) reasons.push("processLimit unlimited");
  if (!Number.isFinite(attestation.fileDescriptorLimit)) reasons.push("fileDescriptorLimit unlimited");
  if (!Number.isFinite(attestation.fileSizeLimitBytes)) reasons.push("fileSizeLimitBytes unlimited");
  const dropped = new Set(attestation.capabilitiesDropped);
  const missing = REQUIRED_DROPPED_CAPABILITIES.filter((c) => !dropped.has(c));
  if (missing.length > 0) {
    reasons.push(`capabilitiesDropped missing ${missing.length} required caps (e.g. ${missing.slice(0, 3).join(", ")})`);
  }
  if (attestation.networkMode !== "hermetic-loopback") {
    reasons.push(`networkMode is ${attestation.networkMode} (required: hermetic-loopback)`);
  }
  if (!attestation.readonlyRootfs) {
    reasons.push("readonlyRootfs is false");
  }
  if (attestation.substrateType === "docker") {
    if (!attestation.imageDigest) reasons.push("docker substrate missing imageDigest");
    if (!attestation.containerId) reasons.push("docker substrate missing containerId");
  }
  return { valid: reasons.length === 0, reasons };
}

export function isSubstrateVerified(
  attestation: SandboxAttestation | null | undefined
): boolean {
  return verifySubstrateAttestation(attestation).valid;
}

/**
 * Phase 18W: Verify the LAUNCHER signature on the substrate attestation.
 *
 * This proves the facts came from the real launcher (which holds the launcher
 * private key), not fabricated by a compromised worker. The worker does NOT
 * have the launcher private key — it is provisioned by admin.
 *
 * Checks:
 *   1. launcherSignature is present.
 *   2. Ed25519 signature is valid over canonicalFactsJson UTF-8 bytes using
 *      the pinned launcher public key.
 *   3. The nonce parsed from canonicalFactsJson === expectedNonce.
 *   4. The executionId parsed from canonicalFactsJson === expectedExecutionId.
 *   5. substrateInstanceId is present in canonicalFactsJson.
 *   6. workloadStdoutHash and workloadStderrHash are present.
 *
 * @param attestation The attestation to verify.
 * @param launcherPublicKeyPem The PINNED launcher public key (provisioned by admin).
 * @param expectedNonce The nonce the control plane expects for this execution.
 * @param expectedExecutionId The executionId the control plane expects.
 */
export function verifyLauncherAttestation(
  attestation: SandboxAttestation | null | undefined,
  launcherPublicKeyPem: string,
  expectedNonce: string,
  expectedExecutionId: string
): SubstrateVerificationResult {
  const reasons: string[] = [];
  if (!attestation) {
    return { valid: false, reasons: ["No substrate attestation provided"] };
  }
  if (!attestation.launcherSignature) {
    reasons.push("launcherSignature is missing");
  }
  if (!attestation.canonicalFactsJson) {
    reasons.push("canonicalFactsJson is missing");
    return { valid: false, reasons };
  }
  if (!launcherPublicKeyPem) {
    reasons.push("launcherPublicKeyPem is empty (not provisioned)");
    return { valid: false, reasons };
  }

  // 1. Verify Ed25519 signature over canonicalFactsJson UTF-8 bytes.
  const data = Buffer.from(attestation.canonicalFactsJson, "utf-8");
  const sigBuf = Buffer.from(attestation.launcherSignature, "hex");
  if (sigBuf.length !== 64) {
    reasons.push(
      `launcherSignature is ${sigBuf.length} bytes (expected 64 for Ed25519)`
    );
  } else {
    let sigValid = false;
    try {
      sigValid = cryptoVerify(null, data, launcherPublicKeyPem, sigBuf);
    } catch (err) {
      reasons.push(
        `signature verification threw: ${err instanceof Error ? err.message : String(err)}`
      );
    }
    if (!sigValid) {
      reasons.push(
        "launcher Ed25519 signature is INVALID for the pinned public key (facts may be fabricated)"
      );
    }
  }

  // 2. Parse canonicalFactsJson and check nonce/executionId/substrateInstanceId.
  let parsed: {
    nonce?: unknown;
    executionId?: unknown;
    substrateInstanceId?: unknown;
    workloadStdoutHash?: unknown;
    workloadStderrHash?: unknown;
  };
  try {
    parsed = JSON.parse(attestation.canonicalFactsJson);
  } catch (err) {
    reasons.push(
      `canonicalFactsJson is not valid JSON: ${err instanceof Error ? err.message : String(err)}`
    );
    return { valid: false, reasons };
  }

  if (parsed.nonce !== expectedNonce) {
    reasons.push(
      `canonicalFactsJson.nonce (${String(parsed.nonce)}) !== expectedNonce (${expectedNonce})`
    );
  }
  if (parsed.executionId !== expectedExecutionId) {
    reasons.push(
      `canonicalFactsJson.executionId (${String(parsed.executionId)}) !== expectedExecutionId (${expectedExecutionId})`
    );
  }
  if (!parsed.substrateInstanceId || typeof parsed.substrateInstanceId !== "string") {
    reasons.push("canonicalFactsJson.substrateInstanceId is missing");
  }
  if (!parsed.workloadStdoutHash || typeof parsed.workloadStdoutHash !== "string") {
    reasons.push("canonicalFactsJson.workloadStdoutHash is missing");
  }
  if (!parsed.workloadStderrHash || typeof parsed.workloadStderrHash !== "string") {
    reasons.push("canonicalFactsJson.workloadStderrHash is missing");
  }

  return { valid: reasons.length === 0, reasons };
}

/**
 * Phase 18W: Returns true ONLY when BOTH:
 *   - verifySubstrateAttestation().valid (the FACTS are valid)
 *   - verifyLauncherAttestation().valid (the LAUNCHER SIGNATURE is valid)
 *
 * This is the production gate for trusted substrate attestation. A compromised
 * worker cannot forge the launcher signature (it doesn't have the launcher
 * private key), so it cannot make isSubstrateTrusted() return true without
 * actually running inside the real substrate.
 */
export function isSubstrateTrusted(
  attestation: SandboxAttestation | null | undefined,
  launcherPublicKeyPem: string,
  expectedNonce: string,
  expectedExecutionId: string
): boolean {
  return (
    verifySubstrateAttestation(attestation).valid &&
    verifyLauncherAttestation(
      attestation,
      launcherPublicKeyPem,
      expectedNonce,
      expectedExecutionId
    ).valid
  );
}

/**
 * Phase 18W: Generate an Ed25519 key pair for the launcher.
 *
 * The launcher key is SEPARATE from the worker key. In production, the admin
 * provisions the launcher private key to the worker (as a file on disk) and
 * the launcher public key to the control plane (pinned in config). The worker
 * NEVER generates its own launcher key — that would defeat the trust model.
 *
 * This function is for dev/test bootstrapping.
 */
export function generateLauncherKeyPair(): {
  privateKeyPem: string;
  publicKeyPem: string;
} {
  const { privateKey, publicKey } = generateKeyPairSync("ed25519");
  return {
    privateKeyPem: privateKey.export({ type: "pkcs8", format: "pem" }).toString(),
    publicKeyPem: publicKey.export({ type: "spki", format: "pem" }).toString(),
  };
}

function canonicalString(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "boolean") return value.toString();
  if (typeof value === "number") return value.toString();
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) {
    return "[" + value.map(canonicalString).join(",") + "]";
  }
  if (typeof value === "object" && value !== null) {
    const v = value as Record<string, unknown>;
    const keys = Object.keys(v).filter((k) => v[k] !== undefined).sort();
    return "{" + keys.map((k) => JSON.stringify(k) + ":" + canonicalString(v[k])).join(",") + "}";
  }
  return "null";
}

/**
 * Phase 18W: Compute the attestation hash — includes ALL fields (old + new
 * launcher-signed fields). This hash is bound into the result hash and
 * envelope hash, so the launcher-signed fields are Ed25519-authenticated by
 * the worker's signature on the envelope.
 */
export function computeAttestationHash(attestation: SandboxAttestation): string {
  const fields = {
    capabilitiesDropped: [...attestation.capabilitiesDropped].sort(),
    canonicalFactsJson: attestation.canonicalFactsJson,
    containerId: attestation.containerId ?? null,
    cpuLimitSeconds: attestation.cpuLimitSeconds,
    createdAt: attestation.createdAt,
    executionId: attestation.executionId,
    fileDescriptorLimit: attestation.fileDescriptorLimit,
    fileSizeLimitBytes: attestation.fileSizeLimitBytes,
    imageDigest: attestation.imageDigest ?? null,
    launcherAlgorithm: attestation.launcherAlgorithm,
    launcherKeyId: attestation.launcherKeyId,
    launcherSignature: attestation.launcherSignature,
    launcherSignedAt: attestation.launcherSignedAt,
    memoryLimitBytes: attestation.memoryLimitBytes,
    mntNamespaceInode: attestation.mntNamespaceInode,
    netNamespaceInode: attestation.netNamespaceInode,
    networkMode: attestation.networkMode,
    nonce: attestation.nonce,
    pidNamespaceInode: attestation.pidNamespaceInode,
    processLimit: attestation.processLimit,
    readonlyRootfs: attestation.readonlyRootfs,
    runtimeVersion: attestation.runtimeVersion,
    seccompMode: attestation.seccompMode,
    seccompProfileHash: attestation.seccompProfileHash,
    substrateInstanceId: attestation.substrateInstanceId,
    substrateType: attestation.substrateType,
    substrateVerified: attestation.substrateVerified,
    userNamespaceInode: attestation.userNamespaceInode,
    workloadExitCode: attestation.workloadExitCode,
    workloadSignal: attestation.workloadSignal,
    workloadStderrHash: attestation.workloadStderrHash,
    workloadStdoutHash: attestation.workloadStdoutHash,
  };
  return createHash("sha256").update(canonicalString(fields)).digest("hex");
}
